#+Title: Best practices - MESA Summer School 2025
#+date: <2025-07-24 Thu>

Materials for the Thursday morning lab at the [[https://mesa-leuven.4d-star.org/][MESA summer school 2025]]
to be held in KU Leuven.

** Debugging

loosely based on [[https://docs.mesastar.org/en/latest/developing/debugging.html][this documentation]].

*Idea*: start from =*.mod= file and study envelope velocities and crashes 
 *Aldana: So this means we are aiming at fixing problems that usually arise in large networks models? I wonder if it won't be better to communicate with the other groups and try get an error that is common in their labs, so we don't need to start explaining new physical concepts*
Maybe show adding drag makes model go? *Aldana: It usually goes toghther with playing with the op_split-burn-min-T, no? Also, playing with Pextra_factor could also help*

*** Testing

Tests in [[./15Msun_late]] *Aldana: the link gives a non-found error and I am not sure where to find this test_suite and add it myself (I didn't see it in the test_suits of mesa-24.08.1)*
Use one core by running

#+begin_src sh
export OMP_NUM_THREADS=1
#+end_src

**** Requirements
 [[https://docs.mesastar.org/en/24.08.1/installation.html][MESA 24.08.1]] (tested with [[http://user.astro.wisc.edu/~townsend/static.php?ref=mesasdk][MESA SDK]] "x86_64-linux-24.7.1")

** Developing
- [[https://github.com/mathren/compare_workdir_MESA][compare inlist ignoring order, comments, nesting, and defaults]] *Aldana: didn't read this part yet*
- going from test case to physically sound setup *Aldana: in this context, to overwhelm the studentsless it might be good to take an inlist they were already exposed to, and show how to get to this inlist starting from a test case. It might not be completely physical since it is simplified so it will run during the lab time, but still better than the test_case I think. Maybe a bonus/to read home could be showing how to this inlist the runs in the lab time and make an acutual physical case out of it (so build this in stages)*


** Open science & reproducibility
Maybe make checklist to consult
- example: [[https://ui.adsabs.harvard.edu/abs/2020ApJ...902L..36F/abstract][Farmer et al. 2020]] \rightarrow [[https://ui.adsabs.harvard.edu/abs/2022ApJ...924...39M/abstract][Mehta et al. 2021]] and
  updates in input physics, Beyond Standard Model Physics in stellar
  explosions *Aldana: I don't underst where the Beyond Standard Model Physics comes into play here*.
- *Aldana: Choice of relevant networks, supper_add_reduction, wind_scheme, etc... *

- [[http://zenodo.org][Zenodo]]:
  - minimal work examples (\rightarrow how to ask a good question on the mailing
    list *Aldana: always attach the inlist/run_star_extras, describe what you tried and where you got stuck*)
  - *Aldana: Another best practice regarding the mailing list: there is not really a good way to look for things in the mailing list before when you joined, look by subject, etc. My advice would be to have a mesa_mailing_list folder in your email and transfer all the related emails there. Then, every time when you get an email from the mailing list at least scheme it before moving it to this folder. Then when you run into a problem you have some key-words to search for from past emails*
  - data: profiles and history *Aldana: work with history columns list and profile columns list. Don't include everything so your data is less heavy, but try to think what you would need for your research so you don't need to keep re-running the same model. Could be a best practice that is not relevant ot Zenodo*
  - postprocessing scripts *Aldana: do we want to recommend to use existing scripts for post-processing? I always find it easier to run my own scripts. But again, best practice bullet that is not necessarily related to Zenodo*
  - README mapping figure/result \leftrightarrow scripts \leftrightarrow data \leftrightarrow code *Aldana: don't dump raw data with many many irrelevant files. Attach the data that is relevant to produce the figures/do the analysis, and offer to send more data upon request.*
- give proper credits in your citation
  - input physics
  - algorithmic implementation
  - /all/ code papers
- consider "donating time" to help others *Aldana: what does this mean? answering in the mailing list? Make your data public in a clear way with instructions? Do PRs for mesa? This can mean many different things*
- *Bonus*: [[https://github.com/MESAHub/mesa-contrib][MESA contrib]]
*Aldana: also regarding Zeonod - make sure to upload to the mesa community in zenodo so your contributions are linked to mesa*

** References

Relevant MESA documentation pages:
- [[https://docs.mesastar.org/en/latest/using_mesa/best_practices.html][Best practices]]
- [[https://docs.mesastar.org/en/latest/developing/debugging.html][Debugging]]
- [[https://zenodo.org/communities/mesa/records?q=&l=list&p=1&s=10][MESA community on zenodo]]
Contribute back ready-to-use routines:
- [[https://github.com/MESAHub/mesa-contrib][MESA contrib]]
Tooling:
- [[https://github.com/mathren/compare_workdir_MESA][compare MESA inlists]]

*Aldana: I think it is a bit confusing to have the references in the end, maybe best to nest them above in the relevant places*



