#!/bin/bash

rm -f restart_photo

echo "Are you sure you want to start from ZAMS? this will be longer than expected!"
echo "You may want to consider running"
echo "       ./re x261"
echo " for the MESA summer school exercise"

read -p "Do you want to proceed from ZAMS anyways? (y/n): " answer
if [[ $answer == "y" || $answer == "Y" ]]; then
    echo "Let's go from ZAMS!"
    date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
    ./star
    date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
else
    echo "Assuming it exists..."
    read -p "...maybe you want to start from photos/x261? (y/n): " answer
    if [[ $answer == "y" || $answer == "Y" ]]; then
    date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
    ./re x261
    date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
    else
	exit 1
    fi
fi
